### ISSUE TITLE
Make textures for the main highway roads. bridge underside etc.

### ISSUE THREAD

**Issue by UncleRito** [Ekozmaster/NFSU2-RTX-Remix#101]
This is the least requirement for the next release.

**Comment by UncleRito** [comment]
This is the least requirement for the next release.

**Comment by HellRaven-Experience** [comment]
Bridge Underside current status: new textures added

![Image](https://github.com/Ekozmaster/NFSU2-RTX-Remix/assets/140925177/bf48f3c0-4b50-476e-b2f1-d7a04e8b3d74)
![Image](https://github.com/Ekozmaster/NFSU2-RTX-Remix/assets/140925177/388524f9-5745-4709-9798-6b8595adf6e4)
![Image](https://github.com/Ekozmaster/NFSU2-RTX-Remix/assets/140925177/ce9266b9-8a8d-41cb-b052-0fa39843a83d)

**Comment by HellRaven-Experience** [comment]
Has be finished
