### ISSUE TITLE
Trash Pile

### ISSUE THREAD

**Issue by Ekozmaster** [Ekozmaster/NFSU2-RTX-Remix#125]
![Image](https://github.com/user-attachments/assets/a9a98104-9805-4144-bec7-41dba62fe7fe)

**Comment by nicklllmedia** [comment]
I'll try to make both these specific assets and some general trash ones to make use of them in city as well

**Comment by nicklllmedia** [comment]
![image](https://github.com/user-attachments/assets/39a2fdda-59c6-470a-8e2f-023f1539bf10)
Done.
**trashPileSet_01.usda** in used to place objects in scene, while **03020000_trashPileSet01.usda** is left for modders as pre-made reference which can copied to your files.
